---
language: python
python: "2.7"
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - dnsutils

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"  
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - /usr/sbin/unbound -h
  - dig -p 5353 foobar-1-1-1-1.pseudo.host @127.0.0.1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
