---

dist: focal

language: python
sudo: required

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

addons:
  apt:
    packages:
    - dnsutils

install:
  # install ansible
  - pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"  
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - /usr/sbin/unbound-checkconf
  - dig foobar-1-1-1-1.pseudo.host @127.0.0.1 -p 5353

after_success:
  - cat /etc/unbound/unbound.conf
  - /usr/sbin/unbound -h

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
