---

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: nobody
    group: nogroup
  with_items:
    - /var/lib/unbound/
    - /etc/unbound/
  become: yes

- name: check if control-keys exists
  stat:
    path: /etc/unbound/unbound_control.key
  register: unbound_control_keys

- name: create control keys
  command: /usr/sbin/unbound-control-setup
  when: unbound_control_keys.stat.exists == False
  become_user: nobody
  become: yes

- name: add unbound.conf
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: 0644
  notify: restart_unbound
  become: yes

- name: add named.cache
  copy:
    src: named.cache.txt
    dest: /var/lib/unbound/named.cache
    mode: 0644
  become_user: nobody
  become: yes
