---

- name: add unbound user
  user:
    name: unbound
    home: /var/lib/unbound
    create_home: no
    system: yes
  become: yes

- name: create /var/lib/unbound/
  file:
    path: /var/lib/unbound/
    state: directory
    mode: 0755
    owner: unbound
    group: unbound
  become: yes

- name: check if control-keys exists
  stat:
    path: /etc/unbound/unbound_control.key
  register: unbound_control_keys
  changed_when: no

- name: create control keys
  command: /usr/sbin/unbound-control-setup
  when: not unbound_control_keys.stat.exists
  become: yes
  changed_when: yes

- name: add unbound.conf
  template:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    mode: 0644
  notify: restart_unbound
  become: yes

- name: fetch named.cache
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/named.cache
    mode: 0644
  become: yes

- name: set daemonopts
  ansible.builtin.copy:
    src: unbound.default
    dest: /etc/default/unbound
  become: yes
