---

- name: Add unbound user
  ansible.builtin.user:
    name: unbound
    home: /var/lib/unbound
    create_home: false
    system: true
  become: true

- name: Create /var/lib/unbound/
  ansible.builtin.file:
    path: /var/lib/unbound/
    state: directory
    mode: '0755'
    owner: unbound
    group: unbound
  become: true

- name: Check if control-keys exists
  ansible.builtin.stat:
    path: /etc/unbound/unbound_control.key
  register: unbound_control_keys
  changed_when: false

- name: Create control keys
  ansible.builtin.command: /usr/sbin/unbound-control-setup
  when: not unbound_control_keys.stat.exists
  become: true
  changed_when: true

- name: Add unbound.conf
  ansible.builtin.template:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    mode: '0644'
  notify: Restart_unbound
  become: true

- name: Fetch named.cache
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/named.cache
    mode: '0644'
  become: true
