---

- import_tasks: backports.yml

- import_tasks: deps.yml

- import_tasks: install.yml

- import_tasks: config.yml

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes
  changed_when: no

- import_tasks: munin-plugin.yml
  when: dpkg_munin_node_check is success
