---

- name: install acl for ansible
  apt:
    name: acl
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes

# this does not work
- name: get current unbound version
  command: /usr/sbin/unbound -h
  register: unbound_version_current
  ignore_errors: yes

- include: unbound.yml
  when: unbound_version_current.stdout is not defined or not unbound_version_current.stdout is search(unbound_version_string_match)

- include: config.yml

- name: check for systemd
  command: systemctl --version
  register: systemctl_version
  ignore_errors: yes

- include: systemd.yml
  when: systemctl_version.rc == 0

- include: sysinitv.yml
  when: systemctl_version.rc != 0

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- include: munin-plugin.yml
  when: dpkg_munin_node_check.rc == 0
