---

- name: Import deps.yml
  ansible.builtin.import_tasks: deps.yml

- name: Import install.yml
  ansible.builtin.import_tasks: install.yml

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml

- name: Check if munin-node is installed
  ansible.builtin.command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: true
  changed_when: false

- name: Import munin-plugin.yml
  ansible.builtin.import_tasks: munin-plugin.yml
  when: dpkg_munin_node_check is success
