---

- name: get current unbound version
  command: /usr/sbin/unbound -h
  register: unbound_current
  ignore_errors: yes

- include: unbound.yml
  when: unbound_current.stderr is not defined or unbound_current.stderr.find("Version {{ unbound_version }}") == -1

- include: config.yml

- name: check for systemd
  command: systemctl --version
  register: systemctl_version
  ignore_errors: yes

- include: systemd.yml
  when: systemctl_version.rc == 0

- include: sysinitv.yml
  when: systemctl_version.rc != 0

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- include: munin-plugin.yml
  when: dpkg_munin_node_check.rc == 0
