---

- name: install acl for ansible
  apt:
    name: acl
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes

- import_tasks: deps.yml

- include_tasks: packages/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.yml

- import_tasks: config.yml

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- import_tasks: munin-plugin.yml
  when: dpkg_munin_node_check is success
