version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    working_directory: ~/ansible-role-unbound/
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: pip3 install ansible ansible-lint
      - run: ansible --version
      - run: ansible-lint --version

      - checkout
      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: /usr/sbin/unbound-checkconf
      - run:
          command: sudo cat /etc/unbound/unbound.conf
          when: on_fail
      - run: dig lifeofguenter.de @127.0.0.1 -p 5353
      - run: cat /etc/unbound/unbound.conf
      - run: /usr/sbin/unbound -V
