---

- name: restart_unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  become: yes

- name: restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: yes
