---

- name: Restart_unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  become: true

- name: Restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: true
