---

- name: install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  vars:
    packages:
      - libevent-2.0-5
      - libssl1.0.0
      - libexpat1
  become: yes
