---

- name: install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - libevent-2.0-5
    - libssl1.1
    - libexpat1
    - libsystemd0
  become: yes
