---

- name: install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  vars:
    packages:
      - libevent-2.0-5
      - libssl1.1
      - libexpat1
      - libsystemd0
  become: yes

- name: install .deb
  apt:
    deb: https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/unbound_{{ unbound_version }}-{{ unbound_build }}_amd64.deb
  notify: restart_unbound
  become: yes

- include_tasks: systemd.yml
